modLoader="javafml"
loaderVersion="${loader_range}"
issueTrackerURL="https://github.com/vancevoj/Mantle/issues"
license="MIT"

[[mods]]
    modId="mantle"
    version="${version}"
    displayName="Mantle"
    authors="Slime Knights"
    description='''
Shared code for Slime Knights mods and others. NeoForge 1.21.1 port.
    '''
    displayURL="https://github.com/vancevoj/Mantle"

[[dependencies.mantle]]
    modId="neoforge"
    type="required"
    versionRange="${neoforge_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.mantle]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_range}"
    ordering="NONE"
    side="BOTH"
